// 지연 로딩 페이지 정의 — router.jsx에서 분리 (react-refresh: 컴포넌트만 export하는 파일).
// 초기 번들에서 제외하고, 방문 시 해당 페이지 코드만 로드. Suspense fallback은 Layout의 <Outlet> 래퍼에서 처리.
import { lazyPage } from './utils/lazyPage';

export const DashboardPage = lazyPage(() => import('./pages/DashboardPage'));
export const AttendancePage = lazyPage(() => import('./pages/attendance/AttendancePage'));
export const AttendanceHistoryPage = lazyPage(() => import('./pages/attendance/AttendanceHistoryPage'));
export const LeaveRequestPage = lazyPage(() => import('./pages/leave/LeaveRequestPage'));
export const LeaveHistoryPage = lazyPage(() => import('./pages/leave/LeaveHistoryPage'));
export const LeaveBalancePage = lazyPage(() => import('./pages/leave/LeaveBalancePage'));
export const TeamReportsPage = lazyPage(() => import('./pages/manage/TeamReportsPage'));
export const ManageTeamPage = lazyPage(() => import('./pages/manage/ManageTeamPage'));
export const MyProjectsPage = lazyPage(() => import('./pages/manage/MyProjectsPage'));
export const ReportsPage = lazyPage(() => import('./pages/admin/ReportsPage'));
export const UnassignedReportPage = lazyPage(() => import('./pages/admin/UnassignedReportPage'));
export const OutsourceManagementPage = lazyPage(() => import('./pages/admin/OutsourceManagementPage'));
export const SiteManagementPage = lazyPage(() => import('./pages/admin/SiteManagementPage'));
export const EventManagementPage = lazyPage(() => import('./pages/admin/EventManagementPage'));
export const LeaveManagementPage = lazyPage(() => import('./pages/admin/LeaveManagementPage'));
export const TotalClosingPage = lazyPage(() => import('./pages/admin/TotalClosingPage'));
export const MarginClosingPage = lazyPage(() => import('./pages/admin/MarginClosingPage'));
export const VehicleLogPage = lazyPage(() => import('./pages/admin/VehicleLogPage'));
export const PurchaseDetailPage = lazyPage(() => import('./pages/admin/PurchaseDetailPage'));
export const SupplierManagementPage = lazyPage(() => import('./pages/admin/SupplierManagementPage'));
export const QuotePage = lazyPage(() => import('./pages/admin/QuotePage'));
export const QuoteFormPage = lazyPage(() => import('./pages/admin/QuoteFormPage'));
export const PurchaseItemPage = lazyPage(() => import('./pages/admin/PurchaseItemPage'));
export const StockPage = lazyPage(() => import('./pages/admin/StockPage'));
export const BomPage = lazyPage(() => import('./pages/admin/BomPage'));
export const BomDetailPage = lazyPage(() => import('./pages/admin/BomDetailPage'));
export const PurchaseTrashPage = lazyPage(() => import('./pages/admin/PurchaseTrashPage'));
export const PurchaseListPage = lazyPage(() => import('./pages/admin/PurchaseListPage'));
export const PurchaseClosedPage = lazyPage(() => import('./pages/admin/PurchaseClosedPage'));
export const StaffHubPage = lazyPage(() => import('./pages/admin/StaffHubPage'));
export const TrashPage = lazyPage(() => import('./pages/admin/TrashPage'));
export const QualityPage = lazyPage(() => import('./pages/admin/QualityPage'));
export const QualitySheetPage = lazyPage(() => import('./pages/quality/QualitySheetPage'));
export const ProductionPage = lazyPage(() => import('./pages/production/ProductionPage'));
export const PanelMaterialsPage = lazyPage(() => import('./pages/production/PanelMaterialsPage'));
export const ShortagePage = lazyPage(() => import('./pages/production/ShortagePage'));
export const MaterialsHubPage = lazyPage(() => import('./pages/production/MaterialsHubPage'));
export const WorkspaceSelectPage = lazyPage(() => import('./pages/WorkspaceSelectPage'));
export const MailSendPage = lazyPage(() => import('./pages/admin/MailSendPage'));
export const PaymentPage = lazyPage(() => import('./pages/admin/PaymentPage'));
export const SiteListPage = lazyPage(() => import('./pages/site/SiteListPage'));
export const SiteClosingPage = lazyPage(() => import('./pages/site/SiteClosingPage'));
export const FileLibraryPage = lazyPage(() => import('./pages/library/FileLibraryPage'));
